-- =============================================================================
-- Rhodes Pipeline · Account Setup (idempotent)
-- Run as ACCOUNTADMIN
-- =============================================================================
USE ROLE ACCOUNTADMIN;

-- ---- Warehouses ------------------------------------------------------------
CREATE WAREHOUSE IF NOT EXISTS RHODES_LOAD_WH
    WITH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE
    INITIALLY_SUSPENDED=TRUE COMMENT='Ingestion workload';
CREATE WAREHOUSE IF NOT EXISTS RHODES_TRANSFORM_WH
    WITH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE
    INITIALLY_SUSPENDED=TRUE COMMENT='dbt transformations';
CREATE WAREHOUSE IF NOT EXISTS RHODES_BI_WH
    WITH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE
    INITIALLY_SUSPENDED=TRUE COMMENT='Streamlit + Cortex queries';

-- ---- Database + Schemas ----------------------------------------------------
CREATE DATABASE IF NOT EXISTS RHODES;
USE DATABASE RHODES;
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;

-- Transfer schema ownership to SYSADMIN (hygiene)
GRANT OWNERSHIP ON SCHEMA RHODES.RAW       TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA RHODES.STAGING   TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA RHODES.ANALYTICS TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE RHODES         TO ROLE SYSADMIN COPY CURRENT GRANTS;

-- ---- Roles -----------------------------------------------------------------
CREATE ROLE IF NOT EXISTS RHODES_LOADER;
CREATE ROLE IF NOT EXISTS RHODES_TRANSFORMER;
CREATE ROLE IF NOT EXISTS RHODES_READER;

-- Role hierarchy: custom roles roll up to SYSADMIN
GRANT ROLE RHODES_LOADER       TO ROLE SYSADMIN;
GRANT ROLE RHODES_TRANSFORMER  TO ROLE SYSADMIN;
GRANT ROLE RHODES_READER       TO ROLE SYSADMIN;


-- ---- Warehouse grants ------------------------------------------------------
GRANT USAGE ON WAREHOUSE RHODES_LOAD_WH      TO ROLE RHODES_LOADER;
GRANT USAGE ON WAREHOUSE RHODES_TRANSFORM_WH TO ROLE RHODES_TRANSFORMER;
GRANT USAGE ON WAREHOUSE RHODES_BI_WH        TO ROLE RHODES_READER;

-- ---- Database grants -------------------------------------------------------
GRANT USAGE ON DATABASE RHODES TO ROLE RHODES_LOADER;
GRANT USAGE ON DATABASE RHODES TO ROLE RHODES_TRANSFORMER;
GRANT USAGE ON DATABASE RHODES TO ROLE RHODES_READER;

-- ---- LOADER: write to RAW only --------------------------------------------
GRANT USAGE, CREATE TABLE, CREATE STAGE, CREATE FILE FORMAT
    ON SCHEMA RHODES.RAW TO ROLE RHODES_LOADER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA RHODES.RAW
    TO ROLE RHODES_LOADER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA RHODES.RAW
    TO ROLE RHODES_LOADER;

-- ---- TRANSFORMER: read RAW, full control of STAGING + ANALYTICS -----------
GRANT USAGE ON SCHEMA RHODES.RAW TO ROLE RHODES_TRANSFORMER;
GRANT SELECT ON ALL TABLES   IN SCHEMA RHODES.RAW TO ROLE RHODES_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RHODES.RAW TO ROLE RHODES_TRANSFORMER;

GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE,
      CREATE FUNCTION, CREATE PROCEDURE, MODIFY
    ON SCHEMA RHODES.STAGING TO ROLE RHODES_TRANSFORMER;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE,
      CREATE FUNCTION, CREATE PROCEDURE, MODIFY
    ON SCHEMA RHODES.ANALYTICS TO ROLE RHODES_TRANSFORMER;

-- ---- READER: read ANALYTICS + use Cortex ----------------------------------
GRANT USAGE ON SCHEMA RHODES.ANALYTICS TO ROLE RHODES_READER;
GRANT SELECT ON ALL TABLES    IN SCHEMA RHODES.ANALYTICS TO ROLE RHODES_READER;
GRANT SELECT ON ALL VIEWS     IN SCHEMA RHODES.ANALYTICS TO ROLE RHODES_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RHODES.ANALYTICS TO ROLE RHODES_READER;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA RHODES.ANALYTICS TO ROLE RHODES_READER;

GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE RHODES_READER;

-- ---- Service users (key-pair auth) ----------------------------------------
-- Generate key pair locally first:
--   openssl genrsa -out rhodes_dbt_key.pem 2048
--   openssl rsa -in rhodes_dbt_key.pem -pubout -out rhodes_dbt_key.pub
-- Paste the public key contents (without the BEGIN/END lines) below.

CREATE USER IF NOT EXISTS DBT_USER
    DEFAULT_ROLE      = RHODES_TRANSFORMER
    DEFAULT_WAREHOUSE = RHODES_TRANSFORM_WH
    DEFAULT_NAMESPACE = RHODES.STAGING
    TYPE              = SERVICE
    RSA_PUBLIC_KEY    = '<PASTE_DBT_PUBLIC_KEY_HERE>'
    COMMENT           = 'Service account for dbt Cloud';

CREATE USER IF NOT EXISTS STREAMLIT_USER
    DEFAULT_ROLE      = RHODES_READER
    DEFAULT_WAREHOUSE = RHODES_BI_WH
    DEFAULT_NAMESPACE = RHODES.ANALYTICS
    TYPE              = SERVICE
    RSA_PUBLIC_KEY    = '<PASTE_STREAMLIT_PUBLIC_KEY_HERE>'
    COMMENT           = 'Service account for Streamlit Cloud';

GRANT ROLE RHODES_TRANSFORMER TO USER DBT_USER;
GRANT ROLE RHODES_READER      TO USER STREAMLIT_USER;